### ISSUE TITLE
Question: Error type?

### ISSUE THREAD

**Issue by Karql** [altmann/FluentResults#103]
Hi!

Maybe I've missed something but I wonder what is the best way to tell the library consumer what error he can expect?
For now error could be anything that inheritance from `IError`.

Suposse that we have an interface:

```c#
public interface IService
{
    Result<SuccessModel> Method();
}
```
Libarary consumer looking at this has no idea what error he can expect.

 In one of the projects I am participating in we use something like this (simplified example).

```c#
public abstract class BaseResultModel<TValue>
{
    public const int Success = 1;
    public const int Failed = 2;

    protected const int LastNumber = 2;

    public int Code { get; set; }

    public TValue Value { get; set; }

    public bool IsSuccess
    {
        get
        {
            return this.Code == BaseResultModel.Success;
        }
    }

    public BaseResultModel()
    {
        Code = BaseResultModel.Failed;
    }

    protected BaseResultModel(int code)
    {
        this.Code = code;
    }
    protected BaseResultModel(bool isSuccess)
    {
        this.Code = isSuccess ? Success : Failed;
    }
}

public class MethodResultModel : BaseResultModel<SuccessModel>
{
    public const int SomethingWentWrong1 = LastNumber+1;
    public const int SomethingWentWrong2 = SomethingWentWrong1+1;
}

public interface IService
{
    MethodResultModel Method();
}

// Example invoke
var result = _service.Method();

result.Code switch {
	MethodResultModel.Success => doSomething(),
	MethodResultModel.SomethingWentWrong1 => handle1(),
	_ => throw new Exception("Failed!");
}
```

Maybe is it good idea to add type for error? `Result<TValue, TError>` 
Or like I've said it is other way to accomplished this that I've missed?

Best regards,
Mateusz

**Comment by altmann** [comment]
Thanks for your good question. I'am busy today, I will respond tomorrow.

**Comment by altmann** [comment]
Hi

For me there are two types of failures, expected and unexpected failures. Unexpected failures are failures which are most caused by infrastructure dir example sqlexception, timeoutexception. In this scenario i want to stop the current Operation and log the failure. Therefore i use die unexpected failures exceptions and mit Fluentresults results. 

In the other hand there are expected failures. For example business validation. We expect that the user type wrong or invalid data and we design the system in a way that we can handle these expected failures. In this scenario we don't want to stop the Operation and log the failure. We want to collect all error messages and display it to the user so that the user is able to correct the input AMD retry IT.

**Comment by Karql** [comment]
Hi again! 😉

> For me there are two types of failures, expected and unexpected failures. Unexpected failures are failures which are most caused by infrastructure for example sqlexception, timeoutexception. In this scenario i want to stop the current Operation and log the failure. Therefore i use for unexpected failures exceptions and not Fluentresults results.

> In the other hand there are expected failures. For example business validation. We expect that the user type wrong or invalid data and we design the system in a way that we can handle these expected failures. In this scenario we don't want to stop the Operation and log the failure. We want to collect all error messages and display it to the user so that the user is able to correct the input and retry it. Here we use Fluentresults results.

Totally agree and I do it in the same way.

> The power of the IError is that you can collect all the different errors which you get from multiple methods. If you set the error type in the result then its typed but it is harder to collect different failures. Is it really important for the consumer to know in which kind of failure (which error type) the operation can fail.

I see your point.  I don't say to always set Error type but to have a possibility to do it.
Something like:

```c#
Result 
Result<TValue>
Result<TValue, TError>
```

Then you can return typed result from method and agregated them to generic one.
With this aproche you have self documented code.

e.g.

```c#
public class UserModel
{
	public string Username { get; set; }
}

public class AddUserError : Error
{
	public const string UserAlreadyExists = "User already exists!";

	public AddUserError(string message)
		: base(message)
	{

	}
}

public interface IUserService
{
    Result<UserModel, AddUserError> AddUser(UserModel user);
}
```

Looking at the interface you know that there is an method `AddUser` which can failed when user already exists.
You don't need the documentation nor source code. 

I've made PR https://github.com/altmann/FluentResults/pull/105 please tell me what do you think about it.

Regards,
Mateusz

**Comment by GiorgioG** [comment]
> We want to collect all error messages and display it to the user so that the user is able to correct the input and retry it. Here we use Fluentresults results.
> Ok, this is my mindset to errorhandling. My question ist now why you want to differentiate between the handling of different expected failures?

First off, I'd like to say thank you for creating FluentResult! 

One situation where you might want to differentiate between the handling of different expected failures is setting the appropriate HTTP status code. Take the following example:

```
public class UserService
{
  public Result<User> GetUserById(int userId)
  {
     try
     {
           var user = dbContext.Users.FirstOrDefault(x=>x.Id==userId);
           if(user==null) return Result.Fail("NOT_FOUND");
           return user;
     } catch (Exception e)
     {
           Logger.LogError(e, "Unable to create user");
           return Result.Error("SYSTEM_ERROR");
     }
  }
}
```
 
In my ASP.NET Core Controller base class I have something like:

 ```
 protected ActionResult ProcessFailedResult(Result result)
{
   if (result == null) return StatusCode(500);
   if (result.Errors.Any(x => x.Message == "SYSTEM_ERROR")) return StatusCode(500);
   if (result.Errors.Any(x => x.Message == "NOT_FOUND")) return NotFound();

    var validationError = result.Errors.FirstOrDefault(x => x.Message == "VALIDATION_ERRORS");
    if (validationError != null) return new BadRequestObjectResult(validationError.Reasons);
    return StatusCode(500);
}
```

My UserController might contain the following method:

```
public ActionResult GetUserById(int userId)
{
   var result = userService.GetUserById(userId);
   if(result.IsFailed) return ProcessFailedResult(result);
   return result.Value;
}
```

**Comment by Karql** [comment]
Hi @GiorgioG!

Thank you for response.

Your example shows **one** error type (just Error) with **different** messages so this exactly meets my case.

Looking at `public Result<User> GetUserById(int userId)` you don't know what messages you can expect. 

For your case I would like to have possibility to do something like this:

```
// generic error for getting data
public class GetDataError : Error
{
	public const string NOT_FOUND = "NOT_FOUND";
	public const string SYSTEM_ERROR = "SYSTEM_ERROR";

	// maybe additional fields
	public int Id { get; set; }

	public GetDataError(string message)
		: base(message)
	{

	}
}

// and inteface for get user
Result<User, GetDataError> GetUserById(int userId);
```

Regards,
Mateusz

**Comment by GiorgioG** [comment]
Hi @Karql!
> Looking at public Result<User> GetUserById(int userId) you don't know what messages you can expect.

Good point. 

> For your case I would like to have possibility to do something like this:
> Result<User, GetDataError> GetUserById(int userId);

Yes that would be nice! That reminds me of Rust's [Result<T,E>](https://doc.rust-lang.org/std/result/) type.

**Comment by Karql** [comment]
Ok I think we need to wait for @altmann response.

**Comment by altmann** [comment]
Sorry that you wait so long for my response. It's currently a challenging time. 

Before we introduce a new feature like this one in FluentResults I want to challenge it because when the feature is released I have to maintain it for a long time. Because of that I want to be sure that its really required. 

> One situation where you might want to differentiate between the handling of different expected failures is setting the appropriate HTTP status code. Take the following example:
> 
> ```
> public class UserService
> {
>   public Result<User> GetUserById(int userId)
>   {
>      try
>      {
>            var user = dbContext.Users.FirstOrDefault(x=>x.Id==userId);
>            if(user==null) return Result.Fail("NOT_FOUND");
>            return user;
>      } catch (Exception e)
>      {
>            Logger.LogError(e, "Unable to create user");
>            return Result.Error("SYSTEM_ERROR");
>      }
>   }
> }
> ```
> 
> In my ASP.NET Core Controller base class I have something like:
> 
> ```
> protected ActionResult ProcessFailedResult(Result result)
> {
>   if (result == null) return StatusCode(500);
>   if (result.Errors.Any(x => x.Message == "SYSTEM_ERROR")) return StatusCode(500);
>   if (result.Errors.Any(x => x.Message == "NOT_FOUND")) return NotFound();
> 
>    var validationError = result.Errors.FirstOrDefault(x => x.Message == "VALIDATION_ERRORS");
>    if (validationError != null) return new BadRequestObjectResult(validationError.Reasons);
>    return StatusCode(500);
> }
> ```
> 
> My UserController might contain the following method:
> 
> ```
> public ActionResult GetUserById(int userId)
> {
>    var result = userService.GetUserById(userId);
>    if(result.IsFailed) return ProcessFailedResult(result);
>    return result.Value;
> }
> ```

I saw these kind of code a lot in the last years in different teams. Why do you catch all exceptions in the class ```UserService```? You catch the exception (=unexpected failure) and convert it to an Result (=expected failure) but this has not much benefit. You return the SYSTEM_ERROR as Result and then you convert it to an HTTP Internal Server Error. 

It my experience it is better to keep unexpected failures unexpected failures. 
What do you want to do if the user is not found => cancel the operation immediately, log it and return HTTP Not Found. 
What do you want to do if an exception is thrown => cancel the operation immediately, log it and return HTTP 500. 
What do you want to do if an business validation failed => collect all the error messages, DON'T log it and return HTTP 400 with the error messages. We don't want to log business validation failures because we don't want to see all failures if the user do something wrong (maxlength, do something in the wrong state, ...) You only want to log errors (=unexpected failures) which are interesting for the developers because these unexpected errors should be analyzed and fixed. 

With this mindset I implement the following code. Its very similar to your scenario but a little bit more complex. 

```
public class UserService
{
  public Result<User> DoSomethingWithUser(int userId)
  {
     var user = dbContext.Users.FirstOrDefault(x=>x.Id==userId);
     if (user==null)
       throw new NotFoundException(x.Id);
    
     // super complex business validation
     if (!user.IsActive)
       return Result.Fail("User is not active.");

     // here some logic

     return user;
  }
}
```

Here the controller action:
```
public ActionResult DoSomethingWithUser(int userId)
{
   var result = userService.DoSomethingWithUser(userId);
   if(result.IsFailed) return BadRequest(result);
   return result.Value;
}

protected ActionResult BadRequest(Result result)
{
   return new BadRequestObjectResult(result.Errors.Select(e => e.Message));
}
```

You see the handling of expected errors is only in your controller actions, services and domain models (very positive argument for me). You don't pollute your business code with try/catch and log statements. 
The handling of unexpected failures is - a little bit hidden - in an ASP.NET global exception handle. Details see [here](https://docs.microsoft.com/en-us/aspnet/web-api/overview/error-handling/web-api-global-error-handling). In the global exception handler you can log the unexpected error and transform it to the correct http error response/code. 

This is my opinion to this topic. We saw that the handling of expected and unexpected errors is completely different (Result vs Exception). I think you also saw that converting an unexpected failure (exception) to an expected failure (result) is not the default scenario. You have to think which error handling behavior you need
- collect the errors, don't log it => Result (expected failure)
- cancel the operation immediately, log it, return http 500 => exception (unexpected failure)

All in all I don't see currently the scenario in that is required to differentiate between different expected failures. The advantage to see in the signature which expected errors can occur in a method is nice but not reqlly required because you don't have to differentate between expected failures. 

Please let me know your opinions. I talked about this topic with a lot of people in the last years and in our current project we also reverted one decision in this area - for example at first we handled NotFound as Result like in your code. After 2 years we changed our decision (based on the experience and some problems) and changed the handling of NotFound from Result to exceptions. Yep live-long learning. :)

**Comment by GiorgioG** [comment]
> Sorry that you wait so long for my response. It's currently a challenging time.

No need to apologize - thank you for taking the time for responding in such a detailed fashion (and for building FluentResults!) For years, every time I went to a new employer inevitably I wound up creating our own 'Response' class.  I got tired of reinventing the wheel and that's how I found FluentResults.

> Before we introduce a new feature like this one in FluentResults I want to challenge it because when the feature is released I have to maintain it for a long time. Because of that I want to be sure that its really required.

Fair enough - it's easy for others to make suggestions when we aren't the ones maintaining it.

> Why do you catch all exceptions in the class UserService?

Generally I have thought of these kinds of services like a black box.  As a consumer of a such a service, I want to give it inputs and have it return results - I never want it to explode in my face if one of the gears inside breaks in the box. I don't know if it's good or bad or appropriate.  You make a valid point that in ASP.NET Core you can use a global exception handler to log unexpected (500) errors.  These services may not be only used in ASP.NET (for example a background job/queue processing) and I prefer not to leave it up to the caller to handle exceptions.  

With respect to NotFound I'd be really curious what problems it caused as a Result vs Exceptions (for my own education.)  

As far as the current issue/suggestion itself I'm starting to talk myself out of it.   I do think there are valid uses cases where you want to produce some alternate behavior that isn't just return a list of errors to the user.  Having said that I'm not sure this proposal is necessary/advantageous for doing so.  I think I can solve my own issue(s) around what status code to return by subclassing Error -> NotFoundError, Forbidden (you're authenticated but not allowed to access this resource) and then use pattern matching in ProcessFailedResult instead of the crude string based ("NOT_FOUND", etc.) error processing I have now. 

Thank you again for your time and thoughtful response!  If there's anything I can do to help let me know.

**Comment by Karql** [comment]
@altmann sory some how I've missed notification about your last reply 😥

When you made last reply I think you missed my comment: https://github.com/altmann/FluentResults/issues/103#issuecomment-957152699 and only replied to @GiorgioG 

I still think that possibility to define error type whould be very good thing.
You can see example in PR I have made: https://github.com/Karql/FluentResults/commit/229acbcf0fe8e47ec790c0058c24b219f693952d#diff-d927f9c0e16be0ec7c4d296be85b095d9dec78fe32bc3861ef99164d4566c885R72

**Comment by altmann** [comment]
Thank you all for the description of your use cases but currently I don't see the requirement to differentiate between different errors. I descriped already my opinion to this topic and I hope it was understandable. 

@Karql I read your answer. I think the maintaining cost is higher then the advantage to have this feature that it is self-documented. 

You described these three types:
> ```cs
> Result 
> Result<TValue>
> Result<TValue, TError>
> ```

One is missing Result<TError> and there we have the problem to conflict with Result<TValue>. Some other libs solve this problem with Result<Unit, TError> or something. Summary: I don't like that much and if I can avoid that then I don't want to introduce this in FluentResults. 

Maybe you get your self-documenting feature if you create a new class ```TypedErrorResult<TError>``` and inherit this class from Result and you create a new class ````TypeErrorResult<TValue, TError>``` and inherit this class from Result<T>. If you add some implicit cast operators to convert automatically from TypeErrorResult and Result I think you will get something what you want. 

```
public TypedErrorResult<MyError> Do()
{
   return Result.Fail(""); //convert Result automatically implicitly to TypeErrorResult<MyError>
}
```

Then you can define your error MyError directly at the Return Type. It is only an idea. I don't implement it and test if its working.
