### ISSUE TITLE
Merge() with Success and Failures

### ISSUE THREAD

**Issue by czuvich** [altmann/FluentResults#106]
Excellent library by the way!  I am using the `Result.Merge()` method with both successful and failed results.  When I check the merged result, I only see the `.Errors` collection populated while the `.Successes` is empty.  Here's an example.  Is this by design?

```
var r = new Result<bool>();
r.WithError("TEST");
var r2 = Result.Fail("ERROR");
var r3 = Result.Fail("FAIL 3");
var r4 = Result.Ok();

var merged = Result.Merge(r, r2, r3, r4);
```

**Comment by altmann** [comment]
Hi @czuvich, thanks for your feedback and creating this issue. 

Merge take all reasons of the results and merge them together to one result. A success result (created with Result.Ok()) contains no reasons in the property ``Reasons``. Therefore ``Merge`` in your scenario take all the errors and ignore the success result because it contains no reasons. In my head it makes sense because the success result contains no relevant information - no success message or something. If the success result contains a success message it is merged to the merged result. 

Whats your scenario? Why do you expect a result at the end with two errors and one empty success reason?

**Comment by czuvich** [comment]
Hi @altmann, 

Thanks for the quick reply for clarifying `Merge()`.  I tried invoking `Result.Ok("SUCCESS")`; however, it does not populate the reasons collection with `"SUCCESS"`.  I think I'm just a bit confused by the API usage.

Having said that, here's my scenario.  I have a domain event that triggers several handlers, and I would like to log the `Result<T>` of each handler.  In some cases, it's ok to have a mixtures of success and errors, but I don't always populate a reason for success.  Is it expected to always populate a reason for success in the Result class?

**Comment by altmann** [comment]
Ah, now I understand your scenario. 

``Result.Ok("SUCCESS")`` doesn't add "SUCCESS" to the Reason list. If you call ``Result.Ok(..)`` with a parameter you **set the value** of the result - that is something different. 

There are two "information channels" in the result pattern:
- Value channel: value is set if its the success case (``Result.Ok(5)``); value is not set if its the failed case (``Result.Fail<int>("error1")``)
- Reason channel: optionally you can add a success if its the success case (``Result.Ok().WithSuccess("mySuccessMessage")``); you add an error if its the failed case (``Result.Fail("error1")``); 

The scenario with ``Result.Ok().WithSuccess("mySuccessMessage")`` is not optimized in the api because I think its very rare. The other scenarios are much more common, therefore these scenarios are optimized in the api. 

So if you want to return a success message use ``Result.Ok().WithSuccess("mySuccessMessage")``. With this call you have your success message in your Reasons list. Don't use ``Result.Ok("SUCCESS");``` because with this call you set the value of the result. The ```Result.Merge(...)`` logic doesn't merge values and reasons, it only merge reasons. 

If something is unclear please let me know.

**Comment by czuvich** [comment]
Thanks for the quick reply and detail explanation.  Everything is clear; however, I'd like to make a few suggestions:

1) Perhaps rename `.Merge()` to `.MergeReasons()`
2) `Merge()` should merge all result data and not just reasons.  I understand this would be a breaking API change though.  I do think there's value merging result values and reasons.

Again thanks.
