### ISSUE TITLE
[Enhancement] Null == Result.Fail

### ISSUE THREAD

**Issue by erman-afacan-deltatre** [altmann/FluentResults#161]
Hi, 

I started to use this library recently I must admit It is brilliant. I wonder if you like the idea of that returning null is equivalent to returning a fail state.

Let's say I have an external method called like
`Result<SomeReferanceType> someResponse = await ExternalMethodCall()`

If the `ExternalMethodCall` function returns null, getting `Result.Fail("reference is null")`  would be nice.

Please let me know if you want me to contribute.

Many thanks

**Comment by altmann** [comment]
Thanks for your feedback. I will think about it in the next days but my current opinion is that it is a very special case,  it is not a behaviour which a dev expect and it is very hard to read. Its some hidden magic. 
Because of that I think its better to not implement it. 

If you have some other ideas please let me know.

**Comment by altmann** [comment]
I talked with some people about this feature and our common opinion it is not a behaviour which a dev would expect from the library. But still thank you for the feedback.
