### ISSUE TITLE
Integrate with FluentValidation

### ISSUE THREAD

**Issue by hamedarab** [altmann/FluentResults#200]
I think it would be good if you 

make cast operator from `FluentValidation.Results.ValidationResult` to `Result` as well as `FluentValidation.Results.ValidationFailure` to `Error` type

**Comment by altmann** [comment]
Hi, thank you for your feedback. I already thought about that one or two years ago. I want to keep FluentResults dependency-free - that means, FluentResults has no dependencies to other frameworks. Why? Because many projects don't use FluentResults in combination with FluentValidation and so I don't want to deliver FluentValidation automatically with FluentResults. 

I hope you understand this. The solution would be that I create another extensions package for example FluentResults.Extensions.FluentValidation but that means effort which I can't deliver now.
