### ISSUE TITLE
'Result' does not contain a definition of 'Ok'

### ISSUE THREAD

**Issue by dmarciano** [altmann/FluentResults#53]
This library looks like it would be very helpful for a project I manage, however I can't get it working.

The project is a C# WebAPI (REST service) project being developed in Visual Studio 2017 (Enterprise Edition) and targets the 4.7.2 version of the .NET Framework.  I installed version 1.6.0 of FluentResults using the NuGet Package Manager built into VS.

In order to just test it quickly I looked at some of the unit tests in the GitHub repository (specifically, the **ResultWithValueTests.cs** file) and tried adding the following line in a method:

```c# var okResult = FluentResults.Result.Ok(5);```

This was taken from line 35 of the **ResultWithValueTests.cs** file.  But the above line causes an error which states:

```
'Result' does not contain a definition for 'Ok'
```
 and the code of the error is CS0117.

I tried clone the FluentResults repository directly from GitHub through VS 2017 and it works fine.  The line does have any problem, but when I try it in my own project.

If anyone has any idea or suggestions on why I a getting this error or what a possible solution is, I would greatly appreciate it.  This library seems like it would help streamline a lot of things in my project, but I can't even get a single line of code to work.

Thank you in advance for any assistance.

**Comment by altmann** [comment]
Hi. 

In v1.6 the factory methods like Ok or Fail are in the static class Results with a s. Results.Ok(...) should work.

I updated already the readme because I will publish v2.0 of fluentresults on nuget in the next days. 

Sorry for the misunderstanding.

**Comment by altmann** [comment]
Here is the old version of the readme https://github.com/altmann/FluentResults/blob/a83c92a67024313189621224aaf543ac2ad50caa/README.md

**Comment by dmarciano** [comment]
@altmann The error did go away when I used ```FluentResults.Results.Ok(5);``` but I still don't understand why in the unit tests class from the GitHub repository ```Result.Ok(5)``` (without an 's') works correctly.

**Comment by altmann** [comment]
In v1.6 the class Results is used. v1.6 is published on nuget. You used this version in your project and therefore Results.Ok() worked and Result.Ok() not. 

In the current master which you see on github are already most of the changes included which will come in v2.0. v2.0 is until now not published on nuget. For example you see the new method Result.Ok(). Results.Ok() ist deprecated in v2.0. You also see already the readme of V2.0 therefore you see Result.Ok() in the readme and not Results.Ok(). 

Once again sorry for the misunderstanding. I know its not a good situation to see on github the readme of v2.0 althought v2.0 is not published yet in nuget. 

Hopefully I find tomorrow some time to publish v2.0 on nuget so that the published version and the readme in github is in sync.

**Comment by dmarciano** [comment]
No problem.  Thank you for the clarification.  I have it working with the initial things I wanted.  I will let you know if I come across any further issues.

Thank You

**Comment by altmann** [comment]
@dmarciano FYI: I published today v2.0 of FluentResults. Documentation (readme) on github is now in sync with the published version on nuget.
