### ISSUE TITLE
Add "WithErrors" methods that accept error object/error message collections?

### ISSUE THREAD

**Issue by wolf8196** [altmann/FluentResults#73]
I've just started with the whole concept of Result objects, and currently trying to use them/learn how to use them in the old pet project of mine.
One thing that I found lacking is the method like .WithErrors, that would accept IEnumerable of either Error objects or error messages. Because there are few places where I already have error collection of some sort, and it would be convenient to attach it to the Result.
Currently I had to write an extension method:
```
    public static class ResultExtensions
    {
        public static Result WithErrors(this Result result, IEnumerable<string> errorMessages)
        {
            foreach (var errorMessage in errorMessages)
            {
                result.WithError(errorMessage);
            }

            return result;
        }
    }
```

What are your thoughts on adding something similar to the library?
Or is there something I've missed?

**Comment by altmann** [comment]
Hi thanks for your feedback! This is interesting. In which scenarios do you use this extension method?

**Comment by wolf8196** [comment]
There are currently 2 instances.
First is after validation. FluentValidation returns ValidationResult obj with errors in it, and I put its error messages into the Result obj.
```
            var validationResult = validator.Validate(model);

            if (!validationResult.IsValid)
            {
                return Result.Fail("Request model is invalid.").WithErrors(validationResult.Errors.Select(x => x.ErrorMessage));
            }
```

The second case is similar. DotLiquid's Template obj contains errors if rendering went wrong.
```
            var parsedTemplate = Template.Parse(template);

            var result = parsedTemplate.Render(Hash.FromDictionary(model));

            if (parsedTemplate.Errors.Any())
            {
                return Result.Fail("Failed to process template.").WithErrors(parsedTemplate.Errors.Select(x => x.Message));
            }
```

**Comment by altmann** [comment]
Thanks for the samples. I will have a look at it tomorrow but I also think that it makes sense to provide a WithErrors(...) method.

**Comment by altmann** [comment]
With the current version of FluentResults you can use the method ```WithReasons(...)``` to pass multiple errors to result. A Reason can be an ```Error``` or a ```Success```. Both types (```Error``` and ```Success```) inherit from type ```Reason```. I know it's not perfect because the intent to add errors is not that much clear as with a method name like ```WithErrors(...)```.

The next version of FluentResults contains new methods to support your scenarios in a more readable way
- Result class
  - ```WithErrors(IEnumerable<string> errors)```
  - ```WithErrors(IEnumerable<Error> errors)```
- Error class
  - ```CausedBy(IEnumerable<string> errors)```
  - ```CausedBy(IEnumerable<Error> errors)```

**Hint**
You create an Result with the message "Request model is invalid." and add multiple errors to this Result object. This causes one flat list of errors in the result object. (list is accessable via ```result.Errors```). If this is that what you want then its fine. 

FluentResults supports a hierarchy of errors. If you use ```Result.Fail(new Error("Request model is invalid.").CausedBy(validationResult.Errors.Select(x => x.ErrorMessage)));``` then you create a hierarchy of errors. ```result.Errors``` contains one error with message "Request model is invalid." The causedBy errors are stored in the ```Reasons``` property of the error itself, accessable for example via ```result.Errors.First().Reasons```.

**Comment by altmann** [comment]
The new version is published https://www.nuget.org/packages/FluentResults/2.3.0

**Comment by wolf8196** [comment]
Thanks for the update. Works great.
About the hierarchy.
At first I wanted to go simpler, and did that flat error list, but after your comment tried the hierarchy, and it does look way better)

**Comment by altmann** [comment]
Thanks for the response. If you have any other feedback please let me know.
