### ISSUE TITLE
Proposal: Refactoring Reasons to c#9 records

### ISSUE THREAD

**Issue by crazycrank** [altmann/FluentResults#79]
I'm currently working on a new project in which we use the FluentResults library a lot.
One of the shortcomings I see is the amount of boilerplate one has to write when working with typed error objects. Immediately I thought, this would be a perfect usecase for records.

Instead of having to write something like
```
public class InvalidIdError : Error {

    public InvalidIdError(int id)
    {
        Id = id;;
    }

    public int Id{ get; }
}
```

this would reduce to 

```
public record InvalidIdError(int Id) : Error { }
```

So this proposal is probably more of a question, if you have already thought about that, and why it would be a good idea or not.

This would obviously lead to a major breaking change in the API, as existing derivations would have to be rewritten to records, but I think from a QoL perspective it could be an interesting way to go.

**Comment by altmann** [comment]
Thanks for your proposal. I'am glad that you see the benefits of the result pattern and that you use FluentResults in your project. 

It's an interesting idea and I think that these Error and Success types would be very good usecases for c# records. Less boilerplate is a big advantage but I also have to evaluate the impacts of such an change to the library. 

I only see one way to support records in FluentResults - changing Reason, Error and Success types to IReason, IError and ISuccess. Why? Records can not be inherited from "normal" c# classes (see https://devblogs.microsoft.com/dotnet/c-9-0-on-the-record/#inheritance). Therefore these new error records have to inherit from the new interface IError. I created today a feature branch called [features/RecordSupport](https://github.com/altmann/FluentResults/tree/features/RecordSupport) in which you see the introduction of IReasons, IError and ISuccess and you also see the breaking changes in the api. [Here](https://github.com/altmann/FluentResults/blob/0829b2711b8026d8a35547230a8d62320b03d6e0/src/FluentResults.Test/SuccessTests.cs#L40) you see your custom record error types. 

Back to breaking changes - almost all usings of Reason, Error and Success types changed to IReason, IError and ISuccess. This would be until now the biggest breaking change in the history of FluentResults. 

If you have some other ideas please let me know. I'am open for discussion because I like records and it would be a cool feature in the long run :)

**Comment by altmann** [comment]
@crazycrank in which .net target framework do you want to use the records? .net 5

**Comment by crazycrank** [comment]
Hey @altmann

First of all, glad you like the idea. I actually forked your repo and tried something similar although we obviously went to different routes, but if you like, you can take a look at my approach here: 

**First to your approach** 
Do I understand this correctly, the interfaces you introduced are 
* to reduce backward compatibility issues with existing users of the library, as existing users could reuse all existing Error classes?
* give users the choice to either derive a record from the IError interface, or derive a class from the Error class?

As this is more a playground, where do you want to go? Is the RecordError record you currently implemented a prototype for the intended base implementation for the record? If so, the intention seems to be to have two different base implementation of the IError interface, one would be the existing Error class, the other the new RecordError record?

**To my approach**
Take a look at my Fork if you like: [crazycrank/FluentResults/records](https://github.com/crazycrank/FluentResults/tree/records)

So, I went a bit more all in with my approach (not having to maintain a public library kind of gives you some freedom 😉 ) 
Basically I ditched everything that existed, and completely rewrote all the Reason classes to records, reimplemented equality, HashCode and ToString to provide an experience that's as close to immutable records as possible. Equality is based on the contents of the MetaData dictionary and the Reasons list, as these would otherwise use reference equality. The same is true for HashCode. ToString() has been adapted to provide as close as possible of an output as the default record implementations would  (while also printing contents of Metadata and Reasons).
The records are also completely immutable, made sure by using ImmutableDictionary and ImmutableList for metadata and reasons. Adding metadata or reasons always return a new object.

I was also thinking about converting Results to records, but I'm not sure this would make sense, as Results currently are really dependent on being mutable. So right now, they are still classes.


**Thoughts**
So, my approach very obviously completely breaks all existing users, even though the required changes aren't that massive, it should (in most cases) be a simple case of replacing class by record for all dervived Errors in a project. Otherwise, the Result and Reasons classes behave mostly the same.

But I think the bigger issue is, how you already mentioned, .net 5.0. It's not possible to use records on anything lower, which I would assume most of the users of your library would be. .NET5 on the other hand also provides some nice additional benefits, e.g. the whole topic of nullability, which I've also annotated the library with.

Before I've seen your answer I was actually going to ask if it would make sense to introduce a clear cut here. Something like keeping the existing Version 3 as a kind of LTS version, and introduce a FluentResults5 (since net5 and a clear cut from the current version) or whatever, based on records, with nullability, without backward compatibility. Also, I would obviously give you full control of the code if you want it, this is still your library. 

I'm not sure if the disadvantage of having to upgrade to .NET5 would outweigh the benefit of having records, while also introducing more complexity in the library, especially from a user-perspective. Users would also have to decide between RecordError and Error as their base, introducing complexitiy on the user side, and error potential would increase if someone uses the wrong base. Also it kind of breaks with the beautiful simplicity your library provides right now.

One last thought, although I have not played around with that. I think it would make the FluentAssertions pretty much obsolete, because structural equality makes it beautifully simple to test for the presence of an error in a result object.

And before you ask. Yes I was bored 😆

**Comment by crazycrank** [comment]
Created a pull request for tracking, obviously don't merge it 😆  #80

**Comment by crazycrank** [comment]
Another though I just had: It could be possible to work with compiler flags, and depending on which framework we are currently in, we either compile to a class or a record. This would bring another set of problems with it though (e.g. as soon as a user updates to net5, he would use the record version, which breaks his application without upgrading the FluentResult library)

**Comment by altmann** [comment]
Thanks for your great input!

Records is a new feature in .NET - it is only available since october. I have currently no idea if this new c# feature will be widely used in the .NET community or if it is only used in some minor scenarios. Based on that uncertainty I think it makes no sense for me to only support records in a .net 5 version of FluentResults and lock out all the people who want to use normal old classes. 

The only way I see currently to support records in FluentResults is with backward compatibility to old classes. I look a little bit in your feature branch and I like some parts like Equality override etc. I will have a look at it in detail in the next days and will think about record support in general. Please let me know if you have some more inputs to this topic.

**Comment by crazycrank** [comment]
I see what you mean regarding record usage, but tbh, I think they will find quick and widespread support in the community, as basically all simple data classes like Dto (or e.g. the Reason objects) get massively reduced in boilerplate, and together with the new with statement they have a really nice and simple feeling to it. But yeah, we'll need to see about that.

Looking forward to your thoughts! If you wanna discuss anything, just hit me up

**Comment by crazycrank** [comment]
So, I'm writing this for the second time now. But I've had some further thoughts regarding the whole topic of backwards compatibility.

The problem with using records for Reason classes is in essence their dependency on .NET 5. And it's not an easily solvable problem. It's not unsolvable, but leads to mostly undesirable side effects. 

There are two ways to use records in your library without fully breaking clients:
* Implementing the necessary infrastructure for records in your project (it only needs a class or two to be working in older .net core SDKs). I don't think this is feasible, so I'm going to ignore that.
* As you proposed, provide a base interface for all these types, and provide a base implementation for records and classes. As clients below .NET5 can't use records, the record implementations must be hidden for clients below, which is achievable using a compiler flag.

This works, but leads to different problem
* It creates effectively two version of your library. One with records and one without, depending on which .NET version you are using
* This leads to code duplication all over the source base, whereas there needs to be extra special care to align behavior between record and class implementations, as users expect them to generally work the same. This also reduces the benefits of using records, as many of it's features aren't usable (e.g. immutability and value equality), except you would reimplement the existing classes to adopt the behavior one would expect with records
* I also think it reduces the usefulness of FluentResults overall, as the mental overhead in usage significantly increases, as one has to decide between two ways to achieve the same goal.
* FYI, this issue ([Planning: Working Set Themes](https://github.com/dotnet/csharplang/issues/4144)) mentions inheritance between records and classes, but there's not even an actual issue attached. So I would not expect anything here before earliest .NET7/C#11, possibly later

To be honest, I don't think there's a good way to go, without breaking with the existing implementation. Which saddens me a bit, because working with my implementation makes the hole error handling so much simpler and consise. Even unit testing, where testing for the appearance of an error in a collection now reduces to `result.Errors.ShouldContain(new CustomError("someValue");` (using Shouldly here, but it's basically identical in all other assertion frameworks as well)

**Comment by altmann** [comment]
I also discussed this topic with some of my co-workers. Our results:
- To support only records as reason types is not possible because of the big breaking change in the public api and in the locked out users which such a change causes. 
- The only way is to find an option to support both - classes and records. 
  - Introduce an interface for Reason, Error and Success and support via these new interfaces classes and records. 
  - The introduction of this interfaces leads to breaking changes. e.g. result.Errors type changed from List<Error> to List<IError>. It is not such a big breaking change but many clients have to adopt their code. 
  - In order that clients can define their custom Error records in one line I have to introduce a base record for error and success. This base record can be included in the FluentResult lib with a compile flag for .NET5 or this base record is included in a new separate Nuget Package (FluentResults.Records or whatever). Both are not perfect - its a decision which I have to deal with the next years because - you know it - of further breaking changes. 

I also agree with all your points which you described in your previous post - not all but most of them were also discussed with my co-workers. 

=> So... I think for now its the best to keep FluentResults as it is - simple without record support. This is not a decision forever. If I see that many developers need record support then we can discuss this topic again. 

**For that please vote if you need record support in FluentResults or not I keep this issue open.** 

@crazycrank Thanks for all the time and the very good arguments. I know its a little bit frustrating have a good idea but it is not viable because of breaking changes.

**Comment by altmann** [comment]
**YES**, I wanna **record support for Error and Success types** in FluentResult and I **accept some breaking changes**. +1 this post

**Comment by crazycrank** [comment]
Yeah I completely understand that, I'd probably make the same decision in your shoes.

I gotta ask you though: How would you feel about me re-releasing FluentResults as a different library?
* I would obviously credit you as the main author, and reference the original FluentResults, and give you complete admin rights over the repo as well
* I would take over the support for the library, although you're of course welcome to join in
* The package would otherwise be completely separate, which allows to keep the existing FluentResults library simple und broadly available, while allowing FluentResults.Records (or whatever) to evolve on .NET 5+ and implement some improvements that wouldn't be available for the existing package, and introduce some breaking changes

I'm also thinking about some other smallish improvements, like making result immutable and introducing some further methods to help with that immutability, but I need to think about these.

Let me know what you think about that.

**Comment by altmann** [comment]
I really understand that you want record support. On the one hand I want to bring the library forwards and on the other hand I have to keep the library stable. Keep the balance between these two directions is sometimes not that easy. 

**FluentResults and record support**
If you need record support then please fork my repo, change it and use it in your project INTERNALLY. I have no problem with that. I already said it, I don't want to implement record support NOW. This is not a decision forever, things will change and therefore it is possible that I will change my decision - for example because of community feedback.

**About re-releasing FluentResults**
You ask me how I would feel about re-releasing. I think you know already my answer - I'am not a big fan of that idea - for me its a weird question and and bring me in a odd situation. Since 2017 I put much energy and time into this library. All my learnings to the result pattern which I made in the previous projects are in this library. 
I hope you respect my work and my decision that re-releasing the library in public with some other functionality is for me not an option. 

The long-term disadvantages which I see ...
- A new lib introduces a more or less implicit or explicit dependency between these libraries (for years)
- Keep the behavior consistent over the libs is hard - making decisions is harder (for years)
- For users it is harder to understand because there are two libs
- etc. I think we already talked about the drawbacks

I want to keep the control in the long run and that I can define the .NET 5 strategy - together with the community - in a way which is okay for me. I heard you but I also heard the feedback from my co-workers. I hope you can accept that.

**Comment by crazycrank** [comment]
Yeah I totally understand that, that's why I asked. I probably would feel similar, after all you put a lot of effort into this project, and I will of course respect your decision. I wanted to ask anyway though. Sorry if that irked you the wrong way, that wasn't my intention.

If you will ever go into the direction of records, please feel free to use anything you see in my PR or get inspired by it. I'd also be to help if you'd like some hands on support.

**Comment by JasonLandbridge** [comment]
Nothing to add, just my appreciation for this very interessting read on this topic. Both "sides" have great arguments and I am excited for the possibiilty of record implementation but stability is indeed a higher priority. 

@crazycrank, you could make a great article about what you have written here and maybe get more feedback on the idea?

**Comment by altmann** [comment]
Maybe in the next major version I will make some breaking changes and introduce Interfaces for Error, Success and Reason. This is the precondition to support error records in fluentresults.

**Comment by carlosmunozrodriguez** [comment]
Sorry for being late for the discussion but actually record struct will definitely be a valuable change that is worth the breaking change.

Currently with Results being classes there is just too many temporary allocations specially when going functional all the way with Bind methods. By making them `readonly record struct` all those allocations will disaapear.

**Comment by carlosmunozrodriguez** [comment]
Also I volunteer for helping with this change if needed.
