### ISSUE TITLE
Question: Is it possible to get/set value, even if result is failed

### ISSUE THREAD

**Issue by yaroslavbres** [altmann/FluentResults#81]
First of all, I want to say, that it is a cool and simple library, which can help to up code readability.

But I faced with undesirable behavior (at least in some situations). Sometimes, throwing an exception when accessing Value is not desirable behavior when the Result is failed. 

Let me describe my case:
I have method when I enumerate some lists and do some actions with items.  As method output, I want to get a list of successfully processed items in Result<ListOfItems>.Value, and Failures in Failures list. I don't stop the flow if I have some failures, just log it in at the end.

I agree, that IsFailed/IsSuccess flags should depend on the existence of Failures, but what the reason to force block get/set Value?

**Comment by altmann** [comment]
Thanks for your feedback and your question. 

First, the reason to force block get Value property ist to

**Comment by altmann** [comment]
Thanks for your feedback and your question. 

First, forcing block get Value property of a failed result and throwing an exception is by design. Most of the other result pattern libraries also implemented this behavior. The reason of this behavior is to prevent bugs. Specially to force the developer to call IsSuccess or IsFailed and only if the result is in success state then the Value property should be called. If you call Value property directly and no exception is thrown then you would return null from the Value property and then you get somewhere a confusing NullReferenceException. This would make the bugfixing harder and it is not transparent. 

Your scenario: I know this scenario and I also have it from time to time. It should be transparent to the consumer of the method that the method can executed successfully or not (=failed) - not both. By design a success result have a valid Value property and contains no errors. A failed result have no Value (throw exception to prevent unwanted bugs) and contains one or more errors. Thats the contract to the consumer of the method. Therefore I would't mix both, have a Value and contain errors. 
Don't stopping the flow if we have successfully processed items and some failed processed items in the list is a special case. From the consumer perspective the method is executed successfully, also if some items not processed correctly. There I would return a success result and the Value type is Dto which contains a list of successful processed items and a list of not successful processed items. 
Another solution would be that you return a list of results - for each item one result.
One another solution is to return the not successfully processed items as errors and the successfully processed items as Success message. See readme, there you will find the usage of Success.

**Comment by yaroslavbres** [comment]
Thank you for the reply. I got your point, It definitely has sense. 
I've chosen to return list of results and process it by caller method
