### ISSUE TITLE
Implicit operator from Result<TValue> to TValue

### ISSUE THREAD

**Issue by pauldbentley** [altmann/FluentResults#84]
Would you consider an implicit operator from `Result<TValue>` to `TValue` which would return a succeeded result?

**Comment by altmann** [comment]
Thanks for giving feedback. On this topic I have a strong opinion, because I have a Domain Driven Design background and made a lot of experiences about Value Object conversions via implicit/explicit operators. 

Implicit operators should succeed successfully in each case. For example int to decimal is safe, no information loss - implicit operator exists. Decimal to int is not safe because there is an information loss - no implicit operator, only an explicit operator exists. 

A result object can be 
- in success state => Result.Ok(4) to TValue is safe. 
- in failed state => Result.Fail<int>("Error") to TValue is not safe because a failed result has no value. If you try to access the Value of a failed state then an exception occur. Only via ValueOrNull property you can access the Value without an exception. 

With this in mind a conversion from a result object to TValue is not safe in each case. Therefore I would not add an implicit operator from Result<TValue> to TValue. 

But maybe I don't see the whole picture. Please show me your scenario.

**Comment by jeffward01** [comment]
> Thanks for giving feedback. On this topic I have a strong opinion, because I have a Domain Driven Design background and made a lot of experiences about Value Object conversions via implicit/explicit operators.
> 
> Implicit operators should succeed successfully in each case. For example int to decimal is safe, no information loss - implicit operator exists. Decimal to int is not safe because there is an information loss - no implicit operator, only an explicit operator exists.
> 
> A result object can be
> 
> * in success state => Result.Ok(4) to TValue is safe.
> * in failed state => Result.Fail("Error") to TValue is not safe because a failed result has no value. If you try to access the Value of a failed state then an exception occur. Only via ValueOrNull property you can access the Value without an exception.
> 
> With this in mind a conversion from a result object to TValue is not safe in each case. Therefore I would not add an implicit operator from Result to TValue.
> 
> But maybe I don't see the whole picture. Please show me your scenario.

------------

![image](https://user-images.githubusercontent.com/12589359/123479717-58d17280-d5cf-11eb-82ed-13e2bea69d83.png)


Hello!

Sorry I dont quite understand, which of these is ok?

It sounds like when you said:

> in failed state => Result.Fail("Error") to TValue is not safe because a failed result has no value. If you try to access the Value of a failed state then an exception occur. Only via ValueOrNull property you can access the Value without an exception.

* That ` return Result.Fail("Item does not exist")` is dangerous and will have errors?


Also, the two methods marked in green underline:

* `Result.Ok(itemDto)`
* `itemDto.ToResult()` 

Are marked as 'Obselete', and the warning says to perform a `.ToResult()` instead, which is what I did in the second example and I still get the warning.

I don't understand this:

1. How do I return a successful Result with an object value?
2. How do I return a failed Result such as ` return Result.Fail("Item does not exist")` 

Can you please update your examples?

Thanks for the great library! 🚀

**Comment by altmann** [comment]
Hello, I'am on vacation so my answer is short. To return an success result with a value you have to use Result<T> as Return type of the method. In your case T is the type of itemDto. Then Result.Ok(..) is right and you have to change the fail method to Result.Fail<T>(...) You find that all in the readme.
