### ISSUE TITLE
Allow ToResult to accept a value

### ISSUE THREAD

**Issue by whortleberrybearer** [altmann/FluentResults#86]
Would it be suitable to add a `ToResult<T>(T value)`  option?  Currently, when using the ToResult it is just using the default value, or the converter is supplied.  For a scenario I have, I would like something other than the default.  e.g., 

```csharp
public Result<bool> DoStuff()
{
    if (something)
    {
        Result fooResult = Foo();

        return fooResult.ToResult(true);
    }

    return Result.Ok(false);
}
```

I have currently worked round this by doing `fooResult.ToResult<bool>().WithValue(true)`.  The implementation would be something like:

```csharp
public Result<TNewValue> ToResult<TNewValue>(TNewValue newValue)
{
    return new Result<TNewValue>()
        .WithReasons(Reasons)
        .WithValue(newValue);
}
```

**Comment by altmann** [comment]
Hi. 

If Foo() returns a failed result (=result with one or more errors) then ToResult(true) would copy the errors and would set the Value of Result<bool> to true. The caller of DoStuff() have in this scenario no chance to access the value because the Result<bool> object contains one or more errors. The reason behind that: If you try to access Value of a failed result you get an exception. You can only access Value without exception if you have a success result. This is by design to prevent hidden bugs, see Fail Fast principle. 

I would try something like that. Please write me back if it was helpful for you or if this suggestion doesn't help you in your scenario. 
```
public Result<bool> DoStuff()
{
    if (something)
    {
        Result fooResult = Foo();
        if (fooResult.IsFailed) return fooResult;

        return Result.Ok(true);
    }

    return Result.Ok(false);
}
```

**Comment by whortleberrybearer** [comment]
Sorry, my explanation may have been a little unclear.  

What you have explained is what I expect the functionality to be.  For the `Result<T>` type, you have a `public Result<TNewValue> ToResult<TNewValue>(Func<TValue, TNewValue> valueConverter = null)` method to convert the value if it is not failed.  My suggestion is to try to replicate the same functionality, but instead of taking a converter, take a raw value.

Based on the [ToResult() that accepts the converter](https://github.com/altmann/FluentResults/blob/355cdb76efddd6c455d9b635affb7da9ed8f25b8/src/FluentResults/Results/Result.cs#L72), my example implementation should have been.

```csharp
public Result<TNewValue> ToResult<TNewValue>(TNewValue newValue)
{
    return new Result<TNewValue>()
        .WithValue(IsFailed ? default : newValue)
        .WithReasons(Reasons);
}
```

**Comment by altmann** [comment]
Ah I see your point. I will introduce this method in the next days.

**Comment by whortleberrybearer** [comment]
I will sort it if you want and put a PR in if you want.

**Comment by altmann** [comment]
Thanks again for your pull request. The new version is building and its on the way. I think it will be on nuget in the next hour.
