### ISSUE TITLE
[Question] Is there a priority list of pending and enhancement features for those who would like to contribute?

### ISSUE THREAD

**Issue by jeffward01** [altmann/FluentResults#90]
Hello! 

I would love to contribute to the project, I am wondering where @altmann you think time should be spent.  Do you have a list of priorities for features? Such as:

- 1.)  Is there a `ToDo` list of features which need to be implemented
- 2.) is there a `Wishlist of Enhancements` which would be nice to have added to the library?

Thanks for the awesome library!

**Comment by altmann** [comment]
Cool, thats great. I organise the open todos/enhancements in the issue list. Currently no open issues are ready to implement.

Signing the nuget package is a topic but for this topic I have to make a research whats the best way to do it because it's a big change for the lib. 
Another topic is c# record support. This is also a big breaking change for the public api in the lib. Therefore its on hold in my head.

**Comment by EnergyNick** [comment]
> Another topic is c# record support. This is also a big breaking change for the public api in the lib. Therefore its on hold in my head.

I also think about it and can participate in the implementation, if necessary)
